## master 브랜치에 변화가 발생할 경우, CI 를 진행합니다.
name: java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/tranding
  VERSION: ${{ github.sha }}
  NAME: iplease-eureka-server
  
jobs:
  docker-build:
    runs-on: ubuntu-latest
    needs: continuous-integration
    steps:
      - uses: actions/checkout@v3
      
      - name: log files
        run: |
          echo | pwd
          echo | ll
      
      
      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
        
      - name: cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx
            
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          
          
      - name: build & push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buidx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          
  continuous-deploy:
    needs: docker-build
    runs-on: [ self-hosted, iplease-eureka ]
    steps: 
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: run docker
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 10010: 10010 -network iplease --ip 172.23.0.101 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}: latest
          
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # setup java
      - name: setup JDK 17
        uses: actions/setup-java@v2
        with: 
          java-version: '17'
          distribution: 'adopt'
      # prepare execute  
      - name: grant execute permission to gradlew
        run: chmod +x gradlew
      # test
      - name: test with gradle
        run: ./gradlew test
      # build
      - name: build with gradle
        run: ./gradlew build -x test
